controllers/AlbumController.php
<?php
namespace app\controllers;

use app\models\Album;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

class AlbumController extends Controller
{
    public function actionIndex() {
        $album_model = new Album();

        //show all images from table `album` DB
        $all_images = ( $all_images = $album_model->getAllImages() ) ? $all_images : null;  //var_dump($all_images);die;

        if(Yii::$app->user->isGuest): //if user is guest - redirect to Home page
            return $this->goHome();
        else:
            return $this->render('index', [ 'login_model'=>$album_model,
                    'all_images'=>$all_images,
                ]
            );  //return $this->render('index'); - testing
        endif;
    }

} //__/class AlbumController

controllers/UserController.php
<?php
namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\Signup; //include model Signup.php
use app\models\Login; //include model Login.php
//use app\models\LoginForm;
//use app\models\ContactForm;

class UserController extends Controller  //or - \yii\web\Controller
{

    /**
     * @return
    */
    public function actionIndex() {
        return $this->render('index');
    } //__/public function actionIndex()


    /** ACTION REGISTRATION USER
     * @return
    */
    public function actionSignup() {  //if( isset($_POST['Signup']) ){ var_dump($_POST['Signup']);die; } - testing
        $signup_model = new Signup();

        if( isset($_POST['Signup']) ){  //or Yii::$app->request->post('Signup')
            //вызываем компонент request,в кот.хранятся результ.запроса $_POST,где есть массив $Signup,сформированный при отправке данных из формы регистрации в /views/user/signup.php
            $signup_model->attributes = Yii::$app->request->post('Signup');  //в $model->attributes ложим данные из $_POST['Signup']
            /*это все равно что написать:
                    $signup_model->username = $_POST['Signup']['username'];
                    $signup_model->email = $_POST['Signup']['email'];
                    $signup_model->password = $_POST['Signup']['password']; */

            /*проверит с-ва $username,$email и $password,при их заполнении данными,на все правила валидации,описанные в модели Signup и вернет true/false*/
            if ($signup_model->validate()) {  //if data is validate - login User in DB & redirect to Home page
                $signup_model->signup();  //save new User to DB
                Yii::$app->session->setFlash('success_signup', 'You have successfully signed up!'); //write in session a message,that will be output in main.php
                return $this->goHome();  //redirect to Home page
            }
        }
        /* or this вместо всего того,что выше
        if( $signup_model->load( Yii::$app->request->post() ) && $signup_model->validate() && $signup_model->rules() ) {
            $signup_model->signup();
            return $this->goHome();
        }
        */

        return $this->render('signup', ['signup_model'=>$signup_model]); //return $this->render('signup'); - testing

    } //__/public function actionSignup()



    /** ACTION LOGINATION USER
     * @return
    */
    public function actionLogin() {  //if( isset($_POST['Login']) ){ var_dump($_POST['Login']);die; } - testing
        if( !Yii::$app->user->isGuest ): return $this->goHome(); endif; //if user is not guest(user is logined) - redirect to Home page

        $login_model = new Login();

        if( isset($_POST['Login']) ){ //or Yii::$app->request->post('Login')
            //var_dump($_POST['Login']);die;
            //вызываем компонент request,в кот.хранятся результ.запроса $_POST,где есть массив $Login,сформированный при отправке данных из формы Логинации(авторизации) в /views/user/login.php
            $login_model->attributes = Yii::$app->request->post('Login');  //в $login_model->attributes ложим данные из $_POST['Login']
            /*это все равно что написать:
                    $login_model->email = $_POST['Login']['email'];
                    $login_model->password = $_POST['Login']['password']; */

            /*проверит с-ва $email и $password,при их заполнении данными,на все правила валидации,описанные в модели Signup и вернет true/false*/
            if ($login_model->validate()) {  //if data is validate
                //var_dump('Success!');die();
                Yii::$app->user->login( $login_model->getUser() );
                Yii::$app->session->setFlash('success_login', 'Welcome to site '); //write in session a message,that will be output in main.php
                return $this->goHome();  //redirect to Home page
            }
        }
        /* or this вместо всего того,что выше
        if( $login_model->load( Yii::$app->request->post() ) && $login_model->validate() && $login_model->rules() ) {
            $login_model->#####();
            return $this->goHome();
        }
        */

        return $this->render('login', ['login_model'=>$login_model]); //return $this->render('login'); - testing
    }


    /** ACTION LOGOUT USER
     * @return
   */
    public function actionLogout() {
        //if(Yii::$app->user->isGuest){
            Yii::$app->user->logout();
            //return $this->redirect('login');  //redirect to login form page
            return $this->goHome(); //redirect to Home page
       // }
    }



} //__/class UsersController

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerMetaTag(['name' => 'keywords', 'content' => 'yii, framework, php']);  ?> <!--Meta tags-->
    <?= Html::csrfMetaTags() ?> <!--защита от ложных запросов с др.сайтов. csrf сод.спец.ключ по которому Yii понимает,что запрос идет именно с этого приложения-->
    <?php // $this->title = 'Home'; title for tab this layout ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<!--IDENTITY if User logined-->
<?php
echo '<br><br>';
if(Yii::$app->user->identity) {  //if user is authentication his data in component Yii::$app->user->identity
//    echo '<br>';
//    echo Yii::$app->user->identity['username']; echo '<br>';
//    echo Yii::$app->user->identity['email']; echo '<br>';
//    echo Yii::$app->user->identity['id'];  echo '<br>';
//    echo Yii::$app->user->identity->getId();  echo '<br>';
//    echo Yii::$app->user->identity['role'];  echo '<br>';
//    echo date('d-m-Y', Yii::$app->user->identity['create']);
}
?>
<!--/IDENTITY if User logined-->

<!--SESSION DATA-->
<?php
//$session = Yii::$app->session; var_dump($session->get('logined_user')); - если что-то писали в сессию

if( $msg_signup = Yii::$app->session->getFlash('success_signup') ):  //flash message from session for successfully signed up of user
    echo '<p class="flash_msg text-center"><span class="text-success">'.$msg_signup.'</span></p>';
endif;

if( $msg_login = Yii::$app->session->getFlash('success_login') ):  //flash message from session for successfully login of user
    echo '<p class="flash_msg text-center"><span class="text-success">'.$msg_login.' <b><i>'.Yii::$app->user->identity['username'].'!</i></b> </span></p>';
endif;
?>
<!--/SESSION DATA-->


<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'LITTUS', //<a href="http://i.ua" target="_blank">FLEXI</a>
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right main_navbsr'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
        //if user is not guest(when user is logged) - show tab "Gallery"
            !Yii::$app->user->isGuest ? ['label' => 'Gallery', 'url' => ['/album/index']]  : '',
            ['label' => 'Contact', 'url' => ['/site/contact']],
            //['label' => 'Registration', 'url' => ['/user/signup']],
            //['label' => 'Login', 'url' => ['/user/login']],
        //if user is not guest(when user is logged) and his is Admin(role=1) - show tab "Admin"
            ( !Yii::$app->user->isGuest && Yii::$app->user->identity->role == 1 ) ?
                ['label' => 'Admin Panel',
                    'items'=> [
                        ['label'=>'Admin Home', 'url'=>['/admin'], 'options'=>['class'=>'test11'] ],
                        ['label'=>'', 'url'=>['/'], 'options'=>['class'=>'divider'] ],  //visual divider
                        ['label'=>'Users', 'url'=>['/admin/user']],
                        ['label'=>'Gallery', 'url'=>['/admin/album']],
                        ['label'=>'Something else', 'url'=>['/admin/else']],
                    ],
                ] : '',

            Yii::$app->user->isGuest ? (
                //['label' => 'Login', 'url' => ['/site/login']]
            ['label' => 'Login', 'url' => ['/user/login']]
            ) : (
                    '<li>'
                    . Html::beginForm(['/user/logout'], 'post', ['class' => 'navbar-form'])
                    . Html::submitButton(
                        'Logout (' . Yii::$app->user->identity->username . ')', //'Logout (' . Yii::$app->user->identity->username . ')',
                        ['class' => 'btn btn-link']
                    )
                    . Html::endForm()
                    . '</li>'
                )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>